stages:
  - verify
  - verify-report

parameter-check:
  stage: verify
  image: python:3-buster
  before_script:
    - 'pip install -r dev-requirements.txt'
  script:
    - python -m unittest

ansible-lint:
  stage: verify
  image: python:3-buster
  before_script:
    - 'pip install ansible-lint'
    - 'mkdir -p verify'
  script:
    - 'ansible-lint -p deploy.yml initial_setup.yml | tee verify/ansible-lint.out'
  artifacts:
    when: on_failure
    paths:
      - verify/ansible-lint.out


ansible-lint-report:
  stage: verify-report
  image: python:3-buster
  dependencies:
    - ansible-lint
  before_script:
    - 'pip install ansible-lint ansible-lint-junit'
  script:
    - 'ansible-lint-junit verify/ansible-lint.out -o verify/report.xml'
  when: on_failure
  artifacts:
    paths:
      - verify/ansible-lint.out
      - verify/report.xml
    reports:
      junit: verify/report.xml
