stages:
  - verify

ansible-lint:
  stage: verify
  image: python:3-buster
  before_script:
    - 'pip install ansible-lint ansible-lint-junit'
    - 'mkdir -p verify'
  script:
    - 'ansible-lint -p *-playbook.yml > verify/ansible-lint.out || true'
    - 'ansible-lint-junit verify/ansible-lint.out -o verify/report.xml'
    - 'ansible-lint *-playbook.yml'
  artifacts:
    reports:
      junit: verify/report.xml
