---
- name: "Déploiement Interface Catalogue"
  hosts: webservers

  vars_files:
    - "{{ playbook_dir }}/defaults/main.yml"

  vars_prompt:
    - name: "ansistrano_maven_artifact_type"
      prompt: |
        Artifact type to deploy :
          - release (default)
          - snapshot
        (ansistrano_maven_artifact_type)
      private: no
      default: "release"

    - name: "ansistrano_maven_artifact_version"
      prompt: |
        Version to deploy (ex: 0.1.2)
        (ansistrano_maven_artifact_version)
      private: no

    - name: "ansistrano_url_password"
      prompt: |
        Password for artifact repository
        (ansistrano_url_password)
      private: yes

  pre_tasks:
    - name: "BPI — Localisation du fichier de configuration"
      delegate_to: localhost
      stat:
        path: "{{ playbook_dir }}/config/main.yml"
      register: config_file

    - name: "BPI — Chargement des valeurs"
      delegate_to: localhost
      include_vars:
        file: "{{ playbook_dir }}/config/main.yml"
      when: config_file.stat.exists

    - name: "BPI — Vérification de la configuration"
      assert:
        that:
          - ansistrano_deploy_to is defined
          - ansistrano_maven_group_id is defined
          - ansistrano_maven_artifact_id is defined
          - ansistrano_url_username is defined
          - app_config_database_host is defined
          - app_config_database_name is defined
          - app_config_database_user is defined
          - app_config_database_password is defined
          - app_config_redis_host is defined
          - app_config_redis_port is defined
          - app_config_ldap_host is defined
          - app_config_ldap_port is defined
          - app_config_ldap_password is defined
          - app_config_mailer_url is defined
          - app_config_mail_sender is defined
          - app_config_reply_to_email is defined
          - app_config_catalog_ws_host is defined

    - name: "DEPLOY — Validate artifact type."
      fail:
        msg: |
          Bad artifact type provided: '{{ ansistrano_maven_artifact_type }}'.
          Valid values: 'release' or 'snapshot'.
          (ansistrano_maven_artifact_type)
      when: ansistrano_maven_artifact_type != "release" and ansistrano_maven_artifact_type != "snapshot"
      delegate_to: localhost

    - name: "DEPLOY — Set repository URL."
      debug:
        msg: "Repo: {{ ansistrano_maven_repository_url }}"
      delegate_to: localhost

    - name: "DEPLOY — Set deployment version."
      set_fact:
        ansistrano_release_version: "{{ [lookup('pipe', 'date -u +%Y%m%d-%H%M%S'),
                                                         ansistrano_maven_artifact_type|upper,
                                                       ansistrano_maven_artifact_version]|join('-') }}"
      run_once: true
      when: ansistrano_release_version is not defined
      delegate_to: localhost

  roles:
    - ansistrano.deploy