---
- name: "INSTALL — Configuration du script de déploiement."

  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "ansistrano_deploy_to"
      prompt: |
        Répertoire dans lequel les versions de l'application seront déployées.
        Le répertoire doit exister et être accessible en lecture & écriture par l'utilisateur courant.

        NOTE: Si la machine de déploiement et le serveur web sont deux machines différentes, le répertoire cible
        ainsi que l'utilisateur devant y accéder doivent exister sur le serveur web.
        (par défaut: /var/www/html/bpi-catalogue)
      private: no
      default: "/var/www/html/bpi-catalogue"

    - name: "ansistrano_maven_group_id"
      prompt: |
        Identifiant du groupe contenant les livrables à installer.
        Exemple : fr.sedona.project-code
      private: no

    - name: "ansistrano_maven_artifact_id"
      prompt: |
        Identifiant des livrables de l'application à déployer.
        Exemple : project-mainmodule
      private: no

    - name: "ansistrano_url_username"
      prompt: Nom d'utilisateur pour l'accès au dépôt d'artefacts
      private: no

    - name: "app_config_database_host"
      prompt: Nom d'hôte / adresse IP du serveur PostgreSQL
      default: "localhost"
      private: no

    - name: "app_config_database_name"
      prompt: Nom de la base PostgreSQL
      private: no

    - name: "app_config_database_user"
      prompt: Nom d'utilisateur PostgreSQL
      private: no

    - name: "app_config_database_password"
      prompt: Mot de passe PostgreSQL
      private: yes

    - name: "app_config_redis_host"
      prompt: Nom d'hôte / adresse IP du serveur Redis
      default: "localhost"
      private: no

    - name: "app_config_redis_port"
      prompt: Port d'écoute du serveur Redis
      default: "6379"
      private: no

    - name: "app_config_ldap_host"
      prompt: Nom d'hôte / adresse IP du serveur LDAP
      default: "localhost"
      private: no

    - name: "app_config_ldap_port"
      prompt: Port d'écoute du serveur LDAP
      default: "6379"
      private: no

    - name: "app_config_ldap_password"
      prompt: Mot de passe du serveur LDAP
      private: yes

    - name: "app_config_mailer_url"
      prompt: |
        Accès au serveur de mail.
        Configuration au format DSN.
        Voir : https://symfony.com/doc/current/reference/configuration/swiftmailer.html

        Par défaut : désactivation des envois emails (null://localhost)
      default: "null://localhost"
      private: no

    - name: "app_config_catalog_ws_host"
      prompt: |
        Nom d'hôte et port du webservice BPI
      default: "10.1.2.120:8080"
      private: no

  tasks:
    - name: "INSTALL — Vérification des valeurs"
      fail:
        msg: "Les identifiants de groupes et livrables ne peuvent être vides."
      when: ansistrano_maven_group_id|length == 0 or ansistrano_maven_artifact_id|length == 0

    - name: "INSTALL — Écriture de la configuration de déploiement"
      template:
        src: "{{ playbook_dir }}/templates/project_vars.yml.j2"
        dest: "{{ playbook_dir }}/config/main.yml"
