---
- include_tasks: maven.yml

- name: ANSISTRANO | maven_unarchive | Set archived file
  set_fact:
    ansistrano_archived_file: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_destination_file }}"

- include_tasks: unarchive.yml
