---
- hosts: webservers

  vars_prompt:
    - name: "ansistrano_maven_artifact_type"
      prompt: |
        Artifact type to deploy :
          - release (default)
          - snapshot
        (ansistrano_maven_artifact_type)
      private: no
      default: "release"

    - name: "ansistrano_maven_artifact_version"
      prompt: |
        Version to deploy (ex: 0.1.2)
        (ansistrano_maven_artifact_version)
      private: no

    - name: "ansistrano_url_password"
      prompt: |
        Password for artifact repository
        (ansistrano_url_password)
      private: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: "DEPLOY — Validate artifact type."
      fail:
        msg: |
          Bad artifact type provided: '{{ ansistrano_maven_artifact_type }}'.
          Valid values: 'release' or 'snapshot'.
          (ansistrano_maven_artifact_type)
      when: ansistrano_maven_artifact_type != "release" and ansistrano_maven_artifact_type != "snapshot"
      delegate_to: localhost

    - name: "DEPLOY — Set repository URL."
      debug:
        msg: "Repo: {{ ansistrano_maven_repository_url }}"
      delegate_to: localhost

    - name: "DEPLOY — Set deployment version."
      set_fact:
        ansistrano_release_version: "{{ ansistrano_maven_artifact_type|upper }}-{{ ansistrano_maven_artifact_version }}-{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
      run_once: true
      when: ansistrano_release_version is not defined
      delegate_to: localhost


  roles:
    - ansistrano.deploy